import {
  Activity,
  Baby,
  BookOpen,
  Bot,
  Briefcase,
  Building2,
  Camera,
  CandlestickChart,
  Car,
  CarFront,
  Circle,
  CircleDot,
  Cloud,
  Coffee,
  CreditCard,
  CupSoda,
  DollarSign,
  Download,
  Gem,
  GraduationCap,
  Heart,
  Home,
  Hospital,
  KeyRound,
  Landmark,
  Mail,
  MessageCircle,
  Moon,
  Newspaper,
  Pizza,
  PlaneLanding,
  PlaneTakeoff,
  Recycle,
  Search,
  Share2,
  ShieldAlert,
  Ship,
  ShoppingCart,
  Siren,
  Smile,
  Smartphone,
  Sprout,
  SquarePlay,
  Store,
  Sun,
  Tag,
  TrainFront,
  Trash2,
  TreePine,
  TrendingUp,
  TriangleAlert,
  UserCheck,
  UserMinus,
  Users,
  Utensils,
  Zap,
  type LucideIcon,
} from "lucide-react";

interface StatIconProps {
  name: string;
  className?: string;
}

const icons: Record<string, LucideIcon> = {
  activity: Activity,
  baby: Baby,
  "circle-dot": CircleDot,
  "trending-up": TrendingUp,
  sun: Sun,
  moon: Moon,
  utensils: Utensils,
  coffee: Coffee,
  heart: Heart,
  tag: Tag,
  "plane-takeoff": PlaneTakeoff,
  "plane-landing": PlaneLanding,
  users: Users,
  car: Car,
  "triangle-alert": TriangleAlert,
  "train-front": TrainFront,
  ship: Ship,
  briefcase: Briefcase,
  "user-minus": UserMinus,
  store: Store,
  building: Building2,
  "user-check": UserCheck,
  search: Search,
  mail: Mail,
  "message-circle": MessageCircle,
  newspaper: Newspaper,
  "play-square": SquarePlay,
  download: Download,
  share: Share2,
  bot: Bot,
  "credit-card": CreditCard,
  "shopping-cart": ShoppingCart,
  landmark: Landmark,
  gem: Gem,
  "dollar-sign": DollarSign,
  "candlestick-chart": CandlestickChart,
  "shield-alert": ShieldAlert,
  siren: Siren,
  hospital: Hospital,
  "graduation-cap": GraduationCap,
  "book-open": BookOpen,
  home: Home,
  cloud: Cloud,
  "tree-pine": TreePine,
  sprout: Sprout,
  recycle: Recycle,
  trash: Trash2,
  zap: Zap,
  pizza: Pizza,
  cup: CupSoda,
  smile: Smile,
  smartphone: Smartphone,
  camera: Camera,
  key: KeyRound,
  "car-front": CarFront,
};

export function StatIcon({ name, className = "h-4 w-4" }: StatIconProps) {
  const Icon = icons[name] ?? Circle;

  return <Icon className={className} aria-hidden="true" />;
}
